INSERT INTO articles (title, content, author_name, created_at, updated_at) VALUES
('Welcome to my blog!', 'Welcome to my personal site! I created this space as both a digital journal and a portfolio where I can document my journey as a junior software engineer. I believe that sharing our stories, our projects, and even our setbacks can help us grow—not just individually, but as a community of learners and doers.

This blog is a place for me to discuss my latest projects, share thoughts on software development trends, and offer a glimpse into my journey as a computer science student. Expect to find a mix of technical tutorials, personal reflections, and commentary on the tech world. Whether you’re here to read about my current projects, or simply connect, I’m glad to have you here!', 'Sami Nouidri', date(), date()),
('The Internet Archive goes down.', 'Most of us are used to seeing websites go down following attacks from malicious actors. However, this time, the target wasn’t just another website—it was the Internet Archive, a digital library with one of the most comprehensive collections of web content in history. This shutdown serves as a stark reminder of the importance of data preservation, as well as the vulnerability of online repositories that are meant to stand as our collective memory.

For students, academics, and the general public alike, the Internet Archive is an essential resource, offering free access to millions of books, videos, images, and web pages that would otherwise be lost to time. It even lets users "time-travel" with the Wayback Machine, exploring older versions of websites to track how content, policies, and even design have evolved over the years.

While the outage has been temporary, it highlights two key points: first, the need for stable and resilient data storage systems; second, the potential impacts if we ever lose access to such a vast repository. Many questions arise: How should we back up the web? What roles should governments and organizations play in protecting it? And for those of us in the tech field, how can we contribute to better, more resilient archives that can withstand modern threats? It’s a reminder that the information age is both fragile and essential, deserving of the same protection we’d afford to physical libraries and archives.', 'Sami Nouidri', date(), date());
